version: '3.7'
services:
    influxdb:
        image: influxdb:2.7
        container_name: influxdb_iot
        volumes:
            - ./influxdbv2:/root/.influxdbv2
        ports:
            - "8086:8086"
        networks:
            - iot-network

    influxdb_cli:
        links:
            - influxdb
        image: influxdb:2.7
        entrypoint: influx setup --bucket test_bucket -t test_token -o test_org --username=test_username --password=test_password --host=http://influxdb:8086 -f
        
        restart: on-failure:20
        depends_on:
            - influxdb
        networks:
            - iot-network

    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto_iot
        ports:
            - "1883:1883"  # MQTT
            - "9001:9001"  # MQTT over WebSocket with WebSockets support
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        environment:
            - MQTT_USERNAME=myuser
            - MQTT_PASSWORD=mypassword
        restart: always

    grafana:
        image: grafana/grafana:latest
        container_name: grafana_iot
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin_password
            - GF_SECURITY_ALLOW_EMBEDDING=true
        ports:
            - '3000:3000'
        volumes:
            - grafana:/var/lib/grafana
        networks:
            - iot-network

volumes:
    grafana:

networks:
    iot-network:
        name: iot-network